// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AppealAssigneeOut
 *
 * Ota-ona murojaat yozayotganda tanlaydigan fan oʻqituvchisi.
 *
 * Roʻyxat SERVERDA quriladi — bolaning darslaridan. Frontend butun
 * xodimlar roʻyxatini olib, oʻzi filtrlashi notoʻgʻri boʻlardi: bu
 * maktabning butun kadrlar tarkibini ota-onaga koʻrsatardi (X-6).
 */
export type AppealAssigneeOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Subject Id
     */
    subject_id: string;
    /**
     * Subject Name
     */
    subject_name: string;
};

/**
 * AppealChildOut
 *
 * Ota-onaning bitta farzandi va unga yozish mumkin boʻlgan xodimlar.
 */
export type AppealChildOut = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Class Name
     */
    class_name: string | null;
    /**
     * Homeroom Teacher Name
     */
    homeroom_teacher_name: string | null;
    /**
     * Teachers
     */
    teachers?: Array<AppealAssigneeOut>;
};

/**
 * AppealCreateIn
 */
export type AppealCreateIn = {
    /**
     * Student Id
     */
    student_id: string;
    target: AppealTarget;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body: string;
    /**
     * Subject Id
     */
    subject_id?: string | null;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
};

/**
 * AppealMessageOut
 */
export type AppealMessageOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Body
     */
    body: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AppealNoteCreateIn
 */
export type AppealNoteCreateIn = {
    kind: ContactKind;
    /**
     * Summary
     */
    summary: string;
    /**
     * About Teacher Id
     */
    about_teacher_id?: string | null;
    /**
     * Teacher Rating
     */
    teacher_rating?: number | null;
    /**
     * Teacher Comment
     */
    teacher_comment?: string | null;
};

/**
 * AppealNoteOut
 *
 * ICHKI qayd — faqat administrator va rahbariyat javobida chiqadi.
 */
export type AppealNoteOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Appeal Id
     */
    appeal_id: string;
    kind: ContactKind;
    /**
     * Summary
     */
    summary: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * About Teacher Id
     */
    about_teacher_id?: string | null;
    /**
     * About Teacher Name
     */
    about_teacher_name?: string | null;
    /**
     * Teacher Rating
     */
    teacher_rating?: number | null;
    /**
     * Teacher Comment
     */
    teacher_comment?: string | null;
};

/**
 * AppealOptionsOut
 *
 * MUR-01 formasi uchun kerak boʻlgan hamma narsa — BITTA soʻrovda.
 *
 * Aks holda forma ochilganda uch-toʻrt soʻrov ketardi: farzandlar, sinf
 * rahbari, fan oʻqituvchilari, fanlar.
 */
export type AppealOptionsOut = {
    /**
     * Children
     */
    children?: Array<AppealChildOut>;
};

/**
 * AppealOut
 *
 * Roʻyxat va kartochka uchun umumiy koʻrinish.
 *
 * `messages` roʻyxatda boʻsh keladi va faqat bitta murojaat ochilganda
 * toʻldiriladi: 100 ta murojaatning barcha yozishmasini bir soʻrovda
 * yuborish ham sekin, ham keraksiz.
 */
export type AppealOut = {
    /**
     * Id
     */
    id: string;
    target: AppealTarget;
    status: AppealStatus;
    /**
     * Title
     */
    title: string;
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Student Name
     */
    student_name: string;
    /**
     * Class Name
     */
    class_name: string | null;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Assignee Id
     */
    assignee_id: string | null;
    /**
     * Assignee Name
     */
    assignee_name: string | null;
    /**
     * Subject Name
     */
    subject_name: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Due At
     */
    due_at: string | null;
    /**
     * Closed At
     */
    closed_at: string | null;
    /**
     * Last Message At
     */
    last_message_at: string | null;
    /**
     * Message Count
     */
    message_count?: number;
    /**
     * Messages
     */
    messages?: Array<AppealMessageOut>;
};

/**
 * AppealStatus
 */
export type AppealStatus = 'new' | 'in_review' | 'answered' | 'closed';

/**
 * AppealSummaryOut
 *
 * Kirish qutisi boshidagi raqamlar — foydalanuvchi kesimida.
 */
export type AppealSummaryOut = {
    /**
     * Total
     */
    total: number;
    /**
     * New
     */
    new: number;
    /**
     * Open
     */
    open: number;
    /**
     * Overdue
     */
    overdue: number;
};

/**
 * AppealTarget
 *
 * Murojaat kimga yoʻnaltirilgan.
 */
export type AppealTarget = 'management' | 'homeroom' | 'subject_teacher';

/**
 * AssignIn
 */
export type AssignIn = {
    /**
     * Assignee Id
     */
    assignee_id: string;
};

/**
 * AttendancePoint
 */
export type AttendancePoint = {
    /**
     * Date
     */
    date: string;
    /**
     * Percent
     */
    percent: number;
};

/**
 * ClassAppealStatOut
 *
 * MUR-06: qaysi sinfda murojaat koʻp.
 */
export type ClassAppealStatOut = {
    /**
     * Class Name
     */
    class_name: string;
    /**
     * Total
     */
    total: number;
    /**
     * Open
     */
    open: number;
    /**
     * To Management
     */
    to_management: number;
    /**
     * To Teachers
     */
    to_teachers: number;
    /**
     * Overdue
     */
    overdue: number;
};

/**
 * ClassRowOut
 */
export type ClassRowOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Homeroom Teacher Name
     */
    homeroom_teacher_name: string | null;
    /**
     * Student Count
     */
    student_count: number;
    /**
     * Attendance Percent
     */
    attendance_percent: number;
    /**
     * Average Grade
     */
    average_grade: number;
};

/**
 * ContactKind
 *
 * Administratorning ichki suhbat qaydi turi (ADM-16).
 */
export type ContactKind = 'phone' | 'in_person' | 'online';

/**
 * DirectorOverviewOut
 */
export type DirectorOverviewOut = {
    /**
     * Total Students
     */
    total_students: number;
    /**
     * Total Teachers
     */
    total_teachers: number;
    /**
     * Total Classes
     */
    total_classes: number;
    /**
     * Attendance Percent
     */
    attendance_percent: number;
    /**
     * Average Grade
     */
    average_grade: number;
    /**
     * Lessons Conducted
     */
    lessons_conducted: number;
    /**
     * Attendance Trend
     */
    attendance_trend: Array<AttendancePoint>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthOut
 */
export type HealthOut = {
    /**
     * Status
     */
    status: 'ok';
};

/**
 * LoginIn
 */
export type LoginIn = {
    /**
     * Login
     */
    login: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MessageCreateIn
 */
export type MessageCreateIn = {
    /**
     * Body
     */
    body: string;
};

/**
 * ReadinessOut
 *
 * Ilova soʻrov qabul qilishga tayyormi.
 *
 * `database` — bazaga soʻrov yuborib tekshiriladi. Ulanish puli boʻsh
 * boʻlsa ham javob beradi: pool_pre_ping yangi ulanish ochadi.
 */
export type ReadinessOut = {
    /**
     * Status
     */
    status: 'ok' | 'degraded';
    /**
     * Database
     */
    database: boolean;
};

/**
 * StatusUpdateIn
 */
export type StatusUpdateIn = {
    status: AppealStatus;
};

/**
 * TeacherRowOut
 */
export type TeacherRowOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Short Name
     */
    short_name: string;
    /**
     * Subjects
     */
    subjects: Array<string>;
    /**
     * Homeroom Class Name
     */
    homeroom_class_name: string | null;
    /**
     * Weekly Hours
     */
    weekly_hours: number;
    /**
     * Lessons Conducted
     */
    lessons_conducted: number;
    /**
     * Average Grade Given
     */
    average_grade_given: number;
    /**
     * Grades Given
     */
    grades_given: number;
};

/**
 * TokenOut
 *
 * Refresh token javob tanasida QAYTMAYDI — httpOnly cookie'da ketadi.
 */
export type TokenOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    user: UserOut;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Login
     */
    login: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Short Name
     */
    short_name: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Must Change Password
     */
    must_change_password: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthLoginData = {
    body: LoginIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenOut;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthRefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenOut;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthMeResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type DirectorOverviewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         *
         * Necha kunlik davr
         */
        days?: number;
    };
    url: '/api/v1/director/overview';
};

export type DirectorOverviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DirectorOverviewError = DirectorOverviewErrors[keyof DirectorOverviewErrors];

export type DirectorOverviewResponses = {
    /**
     * Successful Response
     */
    200: DirectorOverviewOut;
};

export type DirectorOverviewResponse = DirectorOverviewResponses[keyof DirectorOverviewResponses];

export type DirectorClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/director/classes';
};

export type DirectorClassesResponses = {
    /**
     * Response Director Classes
     *
     * Successful Response
     */
    200: Array<ClassRowOut>;
};

export type DirectorClassesResponse = DirectorClassesResponses[keyof DirectorClassesResponses];

export type DirectorTeachersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/director/teachers';
};

export type DirectorTeachersResponses = {
    /**
     * Response Director Teachers
     *
     * Successful Response
     */
    200: Array<TeacherRowOut>;
};

export type DirectorTeachersResponse = DirectorTeachersResponses[keyof DirectorTeachersResponses];

export type AppealsListAppealsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: AppealStatus | null;
        /**
         * Target
         */
        target?: AppealTarget | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/appeals';
};

export type AppealsListAppealsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsListAppealsError = AppealsListAppealsErrors[keyof AppealsListAppealsErrors];

export type AppealsListAppealsResponses = {
    /**
     * Response Appeals List Appeals
     *
     * Successful Response
     */
    200: Array<AppealOut>;
};

export type AppealsListAppealsResponse = AppealsListAppealsResponses[keyof AppealsListAppealsResponses];

export type AppealsCreateAppealData = {
    body: AppealCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/appeals';
};

export type AppealsCreateAppealErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsCreateAppealError = AppealsCreateAppealErrors[keyof AppealsCreateAppealErrors];

export type AppealsCreateAppealResponses = {
    /**
     * Successful Response
     */
    201: AppealOut;
};

export type AppealsCreateAppealResponse = AppealsCreateAppealResponses[keyof AppealsCreateAppealResponses];

export type AppealsAppealsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appeals/summary';
};

export type AppealsAppealsSummaryResponses = {
    /**
     * Successful Response
     */
    200: AppealSummaryOut;
};

export type AppealsAppealsSummaryResponse = AppealsAppealsSummaryResponses[keyof AppealsAppealsSummaryResponses];

export type AppealsStatsClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appeals/stats/classes';
};

export type AppealsStatsClassesResponses = {
    /**
     * Response Appeals Stats Classes
     *
     * Successful Response
     */
    200: Array<ClassAppealStatOut>;
};

export type AppealsStatsClassesResponse = AppealsStatsClassesResponses[keyof AppealsStatsClassesResponses];

export type AppealsComposeOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appeals/options';
};

export type AppealsComposeOptionsResponses = {
    /**
     * Successful Response
     */
    200: AppealOptionsOut;
};

export type AppealsComposeOptionsResponse = AppealsComposeOptionsResponses[keyof AppealsComposeOptionsResponses];

export type AppealsGetAppealData = {
    body?: never;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}';
};

export type AppealsGetAppealErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsGetAppealError = AppealsGetAppealErrors[keyof AppealsGetAppealErrors];

export type AppealsGetAppealResponses = {
    /**
     * Successful Response
     */
    200: AppealOut;
};

export type AppealsGetAppealResponse = AppealsGetAppealResponses[keyof AppealsGetAppealResponses];

export type AppealsAddMessageData = {
    body: MessageCreateIn;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/messages';
};

export type AppealsAddMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsAddMessageError = AppealsAddMessageErrors[keyof AppealsAddMessageErrors];

export type AppealsAddMessageResponses = {
    /**
     * Successful Response
     */
    201: AppealMessageOut;
};

export type AppealsAddMessageResponse = AppealsAddMessageResponses[keyof AppealsAddMessageResponses];

export type AppealsUpdateStatusData = {
    body: StatusUpdateIn;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/status';
};

export type AppealsUpdateStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsUpdateStatusError = AppealsUpdateStatusErrors[keyof AppealsUpdateStatusErrors];

export type AppealsUpdateStatusResponses = {
    /**
     * Successful Response
     */
    200: AppealOut;
};

export type AppealsUpdateStatusResponse = AppealsUpdateStatusResponses[keyof AppealsUpdateStatusResponses];

export type AppealsUpdateAssigneeData = {
    body: AssignIn;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/assignee';
};

export type AppealsUpdateAssigneeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsUpdateAssigneeError = AppealsUpdateAssigneeErrors[keyof AppealsUpdateAssigneeErrors];

export type AppealsUpdateAssigneeResponses = {
    /**
     * Successful Response
     */
    200: AppealOut;
};

export type AppealsUpdateAssigneeResponse = AppealsUpdateAssigneeResponses[keyof AppealsUpdateAssigneeResponses];

export type AppealsListNotesData = {
    body?: never;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/notes';
};

export type AppealsListNotesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsListNotesError = AppealsListNotesErrors[keyof AppealsListNotesErrors];

export type AppealsListNotesResponses = {
    /**
     * Response Appeals List Notes
     *
     * Successful Response
     */
    200: Array<AppealNoteOut>;
};

export type AppealsListNotesResponse = AppealsListNotesResponses[keyof AppealsListNotesResponses];

export type AppealsCreateNoteData = {
    body: AppealNoteCreateIn;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/notes';
};

export type AppealsCreateNoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsCreateNoteError = AppealsCreateNoteErrors[keyof AppealsCreateNoteErrors];

export type AppealsCreateNoteResponses = {
    /**
     * Successful Response
     */
    201: AppealNoteOut;
};

export type AppealsCreateNoteResponse = AppealsCreateNoteResponses[keyof AppealsCreateNoteResponses];

export type ServiceHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type ServiceHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthOut;
};

export type ServiceHealthResponse = ServiceHealthResponses[keyof ServiceHealthResponses];

export type ServiceReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ServiceReadinessResponses = {
    /**
     * Successful Response
     */
    200: ReadinessOut;
};

export type ServiceReadinessResponse = ServiceReadinessResponses[keyof ServiceReadinessResponses];
