// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AppealAssigneeOut
 *
 * Ota-ona murojaat yozayotganda tanlaydigan fan oʻqituvchisi.
 *
 * Roʻyxat SERVERDA quriladi — bolaning darslaridan. Frontend butun
 * xodimlar roʻyxatini olib, oʻzi filtrlashi notoʻgʻri boʻlardi: bu
 * maktabning butun kadrlar tarkibini ota-onaga koʻrsatardi (X-6).
 */
export type AppealAssigneeOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Subject Id
     */
    subject_id: string;
    /**
     * Subject Name
     */
    subject_name: string;
};

/**
 * AppealChildOut
 *
 * Ota-onaning bitta farzandi va unga yozish mumkin boʻlgan xodimlar.
 */
export type AppealChildOut = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Class Name
     */
    class_name: string | null;
    /**
     * Homeroom Teacher Name
     */
    homeroom_teacher_name: string | null;
    /**
     * Teachers
     */
    teachers?: Array<AppealAssigneeOut>;
};

/**
 * AppealCreateIn
 */
export type AppealCreateIn = {
    /**
     * Student Id
     */
    student_id: string;
    target: AppealTarget;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body: string;
    /**
     * Subject Id
     */
    subject_id?: string | null;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
    /**
     * Author Id
     */
    author_id?: string | null;
};

/**
 * AppealMessageOut
 */
export type AppealMessageOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Body
     */
    body: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AppealNoteCreateIn
 */
export type AppealNoteCreateIn = {
    kind: ContactKind;
    /**
     * Summary
     */
    summary: string;
    /**
     * About Teacher Id
     */
    about_teacher_id?: string | null;
    /**
     * Teacher Rating
     */
    teacher_rating?: number | null;
    /**
     * Teacher Comment
     */
    teacher_comment?: string | null;
};

/**
 * AppealNoteOut
 *
 * ICHKI qayd — faqat administrator va rahbariyat javobida chiqadi.
 */
export type AppealNoteOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Appeal Id
     */
    appeal_id: string;
    kind: ContactKind;
    /**
     * Summary
     */
    summary: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * About Teacher Id
     */
    about_teacher_id?: string | null;
    /**
     * About Teacher Name
     */
    about_teacher_name?: string | null;
    /**
     * Teacher Rating
     */
    teacher_rating?: number | null;
    /**
     * Teacher Comment
     */
    teacher_comment?: string | null;
};

/**
 * AppealOptionsOut
 *
 * MUR-01 formasi uchun kerak boʻlgan hamma narsa — BITTA soʻrovda.
 *
 * Aks holda forma ochilganda uch-toʻrt soʻrov ketardi: farzandlar, sinf
 * rahbari, fan oʻqituvchilari, fanlar.
 */
export type AppealOptionsOut = {
    /**
     * Children
     */
    children?: Array<AppealChildOut>;
};

/**
 * AppealOut
 *
 * Roʻyxat va kartochka uchun umumiy koʻrinish.
 *
 * `messages` roʻyxatda boʻsh keladi va faqat bitta murojaat ochilganda
 * toʻldiriladi: 100 ta murojaatning barcha yozishmasini bir soʻrovda
 * yuborish ham sekin, ham keraksiz.
 */
export type AppealOut = {
    /**
     * Id
     */
    id: string;
    target: AppealTarget;
    status: AppealStatus;
    /**
     * Title
     */
    title: string;
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Student Name
     */
    student_name: string;
    /**
     * Class Name
     */
    class_name: string | null;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Assignee Id
     */
    assignee_id: string | null;
    /**
     * Assignee Name
     */
    assignee_name: string | null;
    /**
     * Subject Name
     */
    subject_name: string | null;
    /**
     * Created By Id
     */
    created_by_id?: string | null;
    /**
     * Created By Name
     */
    created_by_name?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Due At
     */
    due_at: string | null;
    /**
     * Closed At
     */
    closed_at: string | null;
    /**
     * Last Message At
     */
    last_message_at: string | null;
    /**
     * Message Count
     */
    message_count?: number;
    /**
     * Messages
     */
    messages?: Array<AppealMessageOut>;
};

/**
 * AppealStatus
 */
export type AppealStatus = 'new' | 'in_review' | 'answered' | 'closed';

/**
 * AppealSummaryOut
 *
 * Kirish qutisi boshidagi raqamlar — foydalanuvchi kesimida.
 */
export type AppealSummaryOut = {
    /**
     * Total
     */
    total: number;
    /**
     * New
     */
    new: number;
    /**
     * Open
     */
    open: number;
    /**
     * Overdue
     */
    overdue: number;
};

/**
 * AppealTarget
 *
 * Murojaat kimga yoʻnaltirilgan.
 */
export type AppealTarget = 'management' | 'homeroom' | 'subject_teacher';

/**
 * AssignIn
 */
export type AssignIn = {
    /**
     * Assignee Id
     */
    assignee_id: string;
};

/**
 * AttendanceMarkIn
 *
 * Butun sinf bitta soʻrovda.
 */
export type AttendanceMarkIn = {
    /**
     * Rows
     */
    rows: Array<AttendanceRowIn>;
    /**
     * Topic
     */
    topic?: string | null;
};

/**
 * AttendanceMarkOut
 *
 * Nima oʻzgargani — ustozga "saqlandi" dan koʻra aniqroq javob.
 */
export type AttendanceMarkOut = {
    /**
     * Created
     */
    created: number;
    /**
     * Updated
     */
    updated: number;
    /**
     * Unchanged
     */
    unchanged: number;
};

/**
 * AttendancePoint
 */
export type AttendancePoint = {
    /**
     * Date
     */
    date: string;
    /**
     * Percent
     */
    percent: number;
};

/**
 * AttendanceRowIn
 */
export type AttendanceRowIn = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Status
     */
    status: 'present' | 'absent' | 'excused' | 'late';
    /**
     * Note
     */
    note?: string | null;
};

/**
 * AttendanceStatOut
 */
export type AttendanceStatOut = {
    /**
     * Total
     */
    total: number;
    /**
     * Present
     */
    present: number;
    /**
     * Absent
     */
    absent: number;
    /**
     * Excused
     */
    excused: number;
    /**
     * Late
     */
    late: number;
    /**
     * Percent
     */
    percent: number;
};

/**
 * BadgeOut
 *
 * Yon menyu uchun: qaysi boʻlimda nechta oʻqilmagan xabar bor.
 */
export type BadgeOut = {
    /**
     * Total
     */
    total: number;
    /**
     * Sections
     */
    sections: {
        [key: string]: number;
    };
};

/**
 * ChangePasswordIn
 *
 * Parolni almashtirish (AUT-08).
 *
 * Eski parol soʻraladi — ochiq qolgan sessiyani topgan odam hisobni
 * butunlay egallab olmasin.
 */
export type ChangePasswordIn = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ChildOut
 *
 * Farzand kartochkasi (OTA-02, almashtirgich).
 *
 * Telefon, manzil va hujjat maydonlari ATAYLAB yoʻq (X-6) — ota-onaga
 * oʻz farzandining sinfi va ismi yetarli, qolgani kerak emas.
 */
export type ChildOut = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Short Name
     */
    short_name: string;
    /**
     * Class Name
     */
    class_name: string;
    /**
     * Relation
     */
    relation: string;
};

/**
 * ClassAppealStatOut
 *
 * MUR-06: qaysi sinfda murojaat koʻp.
 */
export type ClassAppealStatOut = {
    /**
     * Class Name
     */
    class_name: string;
    /**
     * Total
     */
    total: number;
    /**
     * Open
     */
    open: number;
    /**
     * To Management
     */
    to_management: number;
    /**
     * To Teachers
     */
    to_teachers: number;
    /**
     * Overdue
     */
    overdue: number;
};

/**
 * ClassRowOut
 */
export type ClassRowOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Homeroom Teacher Name
     */
    homeroom_teacher_name: string | null;
    /**
     * Student Count
     */
    student_count: number;
    /**
     * Attendance Percent
     */
    attendance_percent: number;
    /**
     * Average Grade
     */
    average_grade: number;
};

/**
 * ContactKind
 *
 * Administratorning ichki suhbat qaydi turi (ADM-16).
 */
export type ContactKind = 'phone' | 'in_person' | 'online';

/**
 * DayAttendanceOut
 *
 * Bitta kunning davomati.
 *
 * Faqat DAVOMAT BELGILANGAN darslar. Ustoz hali belgilamagan dars
 * bu yerga tushmaydi — «kelmadi» deb koʻrsatib ota-onani bekorga
 * xavotirga solmaslik uchun.
 */
export type DayAttendanceOut = {
    /**
     * Date
     */
    date: string;
    /**
     * Lessons
     */
    lessons: Array<LessonStatusOut>;
};

/**
 * DirectorOverviewOut
 */
export type DirectorOverviewOut = {
    /**
     * Total Students
     */
    total_students: number;
    /**
     * Total Teachers
     */
    total_teachers: number;
    /**
     * Total Classes
     */
    total_classes: number;
    /**
     * Attendance Percent
     */
    attendance_percent: number;
    /**
     * Average Grade
     */
    average_grade: number;
    /**
     * Lessons Conducted
     */
    lessons_conducted: number;
    /**
     * Attendance Trend
     */
    attendance_trend: Array<AttendancePoint>;
};

/**
 * GuardianOptionOut
 *
 * Oʻquvchining vasiy hisobi — yozishma kimga borishini tanlash uchun.
 */
export type GuardianOptionOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Relation
     */
    relation: string;
    /**
     * Is Primary
     */
    is_primary: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthOut
 */
export type HealthOut = {
    /**
     * Status
     */
    status: 'ok';
};

/**
 * LessonAttendanceOut
 */
export type LessonAttendanceOut = {
    /**
     * Lesson Id
     */
    lesson_id: string;
    /**
     * Class Name
     */
    class_name: string;
    /**
     * Subject Name
     */
    subject_name: string;
    /**
     * Lesson Date
     */
    lesson_date: string;
    /**
     * Period
     */
    period: number;
    /**
     * Room
     */
    room: string | null;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Ends At
     */
    ends_at: string;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Marked At
     */
    marked_at: string | null;
    /**
     * Editable
     */
    editable: boolean;
    /**
     * Edit Deadline
     */
    edit_deadline: string;
    /**
     * Students
     */
    students: Array<StudentRowOut>;
};

/**
 * LessonStatusOut
 */
export type LessonStatusOut = {
    /**
     * Period
     */
    period: number;
    /**
     * Subject
     */
    subject: string;
    /**
     * Status
     */
    status: 'present' | 'absent' | 'excused' | 'late';
    /**
     * Note
     */
    note: string | null;
};

/**
 * LoginIn
 */
export type LoginIn = {
    /**
     * Login
     */
    login: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MarkAllReadIn
 */
export type MarkAllReadIn = {
    /**
     * Section
     */
    section?: string | null;
};

/**
 * MarkReadIn
 */
export type MarkReadIn = {
    /**
     * Ids
     */
    ids: Array<string>;
};

/**
 * MarkReadOut
 */
export type MarkReadOut = {
    /**
     * Updated
     */
    updated: number;
};

/**
 * MessageCreateIn
 */
export type MessageCreateIn = {
    /**
     * Body
     */
    body: string;
};

/**
 * NotificationKind
 *
 * Nima yuz berdi.
 *
 * Tur — bu SABAB, boʻlim emas. Boʻlim (`section`) qabul qiluvchining
 * kabinetiga qarab hisoblanadi: bitta «kelmadi» hodisasi ota-onada
 * «Davomat», oʻquvchida «Bosh sahifa» boʻlimida koʻrinadi.
 */
export type NotificationKind = 'attendance_absent' | 'attendance_late' | 'appeal_new' | 'appeal_message' | 'appeal_assigned' | 'appeal_closed';

/**
 * NotificationOut
 */
export type NotificationOut = {
    /**
     * Id
     */
    id: string;
    kind: NotificationKind;
    /**
     * Kind Label
     */
    kind_label: string;
    /**
     * Section
     */
    section: string;
    /**
     * Link
     */
    link: string;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body: string;
    /**
     * Student Id
     */
    student_id: string | null;
    /**
     * Student Name
     */
    student_name: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Read At
     */
    read_at: string | null;
};

/**
 * PermissionOut
 *
 * Huquq va uning oʻzbekcha izohi.
 */
export type PermissionOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Label
     */
    label: string;
    /**
     * Group
     */
    group: string;
};

/**
 * ReadinessOut
 *
 * Ilova soʻrov qabul qilishga tayyormi.
 *
 * `database` — bazaga soʻrov yuborib tekshiriladi. Ulanish puli boʻsh
 * boʻlsa ham javob beradi: pool_pre_ping yangi ulanish ochadi.
 */
export type ReadinessOut = {
    /**
     * Status
     */
    status: 'ok' | 'degraded';
    /**
     * Database
     */
    database: boolean;
};

/**
 * SectionOut
 *
 * Reyestrdagi bitta boʻlim.
 */
export type SectionOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Cabinet
     */
    cabinet: string;
    /**
     * Locked
     */
    locked: boolean;
    /**
     * Superadmin Only
     */
    superadmin_only: boolean;
};

/**
 * SetPermissionsIn
 *
 * Toʻliq roʻyxat — qoʻshish/olib tashlash emas.
 */
export type SetPermissionsIn = {
    /**
     * Permissions
     */
    permissions?: Array<string>;
};

/**
 * SetSectionsIn
 *
 * `None` — istisnoni bekor qilib rol standartiga qaytarish.
 */
export type SetSectionsIn = {
    /**
     * Sections
     */
    sections?: Array<string> | null;
};

/**
 * StatusUpdateIn
 */
export type StatusUpdateIn = {
    status: AppealStatus;
};

/**
 * StudentRowOut
 *
 * Roʻyxatdagi bitta oʻquvchi va uning holati.
 *
 * Telefon, manzil va hujjat maydonlari ATAYLAB yoʻq (X-6): bu roʻyxat
 * endpointi, shaxsiy maʼlumot faqat bitta oʻquvchi kartochkasida.
 */
export type StudentRowOut = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Status
     */
    status?: 'present' | 'absent' | 'excused' | 'late' | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * StudentSearchOut
 *
 * ADM-16 qidiruvi. X-6: telefon, manzil va hujjat raqami yoʻq.
 */
export type StudentSearchOut = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Class Name
     */
    class_name: string | null;
    /**
     * Guardians
     */
    guardians?: Array<GuardianOptionOut>;
};

/**
 * StudentStatOut
 */
export type StudentStatOut = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Full Name
     */
    full_name: string;
    stat: AttendanceStatOut;
};

/**
 * TeacherLessonOut
 */
export type TeacherLessonOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Class Name
     */
    class_name: string;
    /**
     * Subject Name
     */
    subject_name: string;
    /**
     * Period
     */
    period: number;
    /**
     * Room
     */
    room: string | null;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Ends At
     */
    ends_at: string;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Marked
     */
    marked: boolean;
    /**
     * Editable
     */
    editable: boolean;
    /**
     * Student Count
     */
    student_count: number;
    /**
     * Present Count
     */
    present_count: number;
};

/**
 * TeacherRowOut
 */
export type TeacherRowOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Short Name
     */
    short_name: string;
    /**
     * Subjects
     */
    subjects: Array<string>;
    /**
     * Homeroom Class Name
     */
    homeroom_class_name: string | null;
    /**
     * Weekly Hours
     */
    weekly_hours: number;
    /**
     * Lessons Conducted
     */
    lessons_conducted: number;
    /**
     * Average Grade Given
     */
    average_grade_given: number;
    /**
     * Grades Given
     */
    grades_given: number;
};

/**
 * TokenOut
 *
 * Refresh token javob tanasida QAYTMAYDI — httpOnly cookie'da ketadi.
 */
export type TokenOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    user: UserOut;
};

/**
 * UserAccessOut
 *
 * Foydalanuvchining toʻliq kirish holati.
 */
export type UserAccessOut = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Login
     */
    login: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Cabinet
     */
    cabinet: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Archived
     */
    is_archived: boolean;
    /**
     * Sections
     */
    sections: Array<string>;
    /**
     * Default Sections
     */
    default_sections: Array<string>;
    /**
     * Customized
     */
    customized: boolean;
    /**
     * Permissions
     */
    permissions: Array<string>;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Login
     */
    login: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Short Name
     */
    short_name: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Must Change Password
     */
    must_change_password: boolean;
    /**
     * Cabinet
     */
    cabinet?: string;
    /**
     * Sections
     */
    sections?: Array<string>;
    /**
     * Permissions
     */
    permissions?: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthLoginData = {
    body: LoginIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenOut;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthRefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenOut;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthMeResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthChangePasswordData = {
    body: ChangePasswordIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password';
};

export type AuthChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthChangePasswordError = AuthChangePasswordErrors[keyof AuthChangePasswordErrors];

export type AuthChangePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthChangePasswordResponse = AuthChangePasswordResponses[keyof AuthChangePasswordResponses];

export type AccessSectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/access/sections';
};

export type AccessSectionsResponses = {
    /**
     * Response Access Sections
     *
     * Successful Response
     */
    200: Array<SectionOut>;
};

export type AccessSectionsResponse = AccessSectionsResponses[keyof AccessSectionsResponses];

export type AccessPermissionRegistryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/access/permissions';
};

export type AccessPermissionRegistryResponses = {
    /**
     * Response Access Permission Registry
     *
     * Successful Response
     */
    200: Array<PermissionOut>;
};

export type AccessPermissionRegistryResponse = AccessPermissionRegistryResponses[keyof AccessPermissionRegistryResponses];

export type AccessUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         *
         * Login yoki ism boʻyicha qidirish
         */
        q?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/access/users';
};

export type AccessUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccessUsersError = AccessUsersErrors[keyof AccessUsersErrors];

export type AccessUsersResponses = {
    /**
     * Response Access Users
     *
     * Successful Response
     */
    200: Array<UserAccessOut>;
};

export type AccessUsersResponse = AccessUsersResponses[keyof AccessUsersResponses];

export type AccessUserAccessData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/access/users/{user_id}';
};

export type AccessUserAccessErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccessUserAccessError = AccessUserAccessErrors[keyof AccessUserAccessErrors];

export type AccessUserAccessResponses = {
    /**
     * Successful Response
     */
    200: UserAccessOut;
};

export type AccessUserAccessResponse = AccessUserAccessResponses[keyof AccessUserAccessResponses];

export type AccessSetSectionsData = {
    body: SetSectionsIn;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/access/users/{user_id}/sections';
};

export type AccessSetSectionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccessSetSectionsError = AccessSetSectionsErrors[keyof AccessSetSectionsErrors];

export type AccessSetSectionsResponses = {
    /**
     * Successful Response
     */
    200: UserAccessOut;
};

export type AccessSetSectionsResponse = AccessSetSectionsResponses[keyof AccessSetSectionsResponses];

export type AccessSetPermissionsData = {
    body: SetPermissionsIn;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/access/users/{user_id}/permissions';
};

export type AccessSetPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccessSetPermissionsError = AccessSetPermissionsErrors[keyof AccessSetPermissionsErrors];

export type AccessSetPermissionsResponses = {
    /**
     * Successful Response
     */
    200: UserAccessOut;
};

export type AccessSetPermissionsResponse = AccessSetPermissionsResponses[keyof AccessSetPermissionsResponses];

export type DirectorOverviewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         *
         * Necha kunlik davr
         */
        days?: number;
    };
    url: '/api/v1/director/overview';
};

export type DirectorOverviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DirectorOverviewError = DirectorOverviewErrors[keyof DirectorOverviewErrors];

export type DirectorOverviewResponses = {
    /**
     * Successful Response
     */
    200: DirectorOverviewOut;
};

export type DirectorOverviewResponse = DirectorOverviewResponses[keyof DirectorOverviewResponses];

export type DirectorClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/director/classes';
};

export type DirectorClassesResponses = {
    /**
     * Response Director Classes
     *
     * Successful Response
     */
    200: Array<ClassRowOut>;
};

export type DirectorClassesResponse = DirectorClassesResponses[keyof DirectorClassesResponses];

export type DirectorTeachersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/director/teachers';
};

export type DirectorTeachersResponses = {
    /**
     * Response Director Teachers
     *
     * Successful Response
     */
    200: Array<TeacherRowOut>;
};

export type DirectorTeachersResponse = DirectorTeachersResponses[keyof DirectorTeachersResponses];

export type AppealsListAppealsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: AppealStatus | null;
        /**
         * Target
         */
        target?: AppealTarget | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/appeals';
};

export type AppealsListAppealsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsListAppealsError = AppealsListAppealsErrors[keyof AppealsListAppealsErrors];

export type AppealsListAppealsResponses = {
    /**
     * Response Appeals List Appeals
     *
     * Successful Response
     */
    200: Array<AppealOut>;
};

export type AppealsListAppealsResponse = AppealsListAppealsResponses[keyof AppealsListAppealsResponses];

export type AppealsCreateAppealData = {
    body: AppealCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/appeals';
};

export type AppealsCreateAppealErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsCreateAppealError = AppealsCreateAppealErrors[keyof AppealsCreateAppealErrors];

export type AppealsCreateAppealResponses = {
    /**
     * Successful Response
     */
    201: AppealOut;
};

export type AppealsCreateAppealResponse = AppealsCreateAppealResponses[keyof AppealsCreateAppealResponses];

export type AppealsAppealsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appeals/summary';
};

export type AppealsAppealsSummaryResponses = {
    /**
     * Successful Response
     */
    200: AppealSummaryOut;
};

export type AppealsAppealsSummaryResponse = AppealsAppealsSummaryResponses[keyof AppealsAppealsSummaryResponses];

export type AppealsStatsClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appeals/stats/classes';
};

export type AppealsStatsClassesResponses = {
    /**
     * Response Appeals Stats Classes
     *
     * Successful Response
     */
    200: Array<ClassAppealStatOut>;
};

export type AppealsStatsClassesResponse = AppealsStatsClassesResponses[keyof AppealsStatsClassesResponses];

export type AppealsComposeOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appeals/options';
};

export type AppealsComposeOptionsResponses = {
    /**
     * Successful Response
     */
    200: AppealOptionsOut;
};

export type AppealsComposeOptionsResponse = AppealsComposeOptionsResponses[keyof AppealsComposeOptionsResponses];

export type AppealsSearchStudentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Ism yoki familiya
         */
        q: string;
    };
    url: '/api/v1/appeals/students';
};

export type AppealsSearchStudentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsSearchStudentsError = AppealsSearchStudentsErrors[keyof AppealsSearchStudentsErrors];

export type AppealsSearchStudentsResponses = {
    /**
     * Response Appeals Search Students
     *
     * Successful Response
     */
    200: Array<StudentSearchOut>;
};

export type AppealsSearchStudentsResponse = AppealsSearchStudentsResponses[keyof AppealsSearchStudentsResponses];

export type AppealsGetAppealData = {
    body?: never;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}';
};

export type AppealsGetAppealErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsGetAppealError = AppealsGetAppealErrors[keyof AppealsGetAppealErrors];

export type AppealsGetAppealResponses = {
    /**
     * Successful Response
     */
    200: AppealOut;
};

export type AppealsGetAppealResponse = AppealsGetAppealResponses[keyof AppealsGetAppealResponses];

export type AppealsAddMessageData = {
    body: MessageCreateIn;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/messages';
};

export type AppealsAddMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsAddMessageError = AppealsAddMessageErrors[keyof AppealsAddMessageErrors];

export type AppealsAddMessageResponses = {
    /**
     * Successful Response
     */
    201: AppealMessageOut;
};

export type AppealsAddMessageResponse = AppealsAddMessageResponses[keyof AppealsAddMessageResponses];

export type AppealsUpdateStatusData = {
    body: StatusUpdateIn;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/status';
};

export type AppealsUpdateStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsUpdateStatusError = AppealsUpdateStatusErrors[keyof AppealsUpdateStatusErrors];

export type AppealsUpdateStatusResponses = {
    /**
     * Successful Response
     */
    200: AppealOut;
};

export type AppealsUpdateStatusResponse = AppealsUpdateStatusResponses[keyof AppealsUpdateStatusResponses];

export type AppealsUpdateAssigneeData = {
    body: AssignIn;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/assignee';
};

export type AppealsUpdateAssigneeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsUpdateAssigneeError = AppealsUpdateAssigneeErrors[keyof AppealsUpdateAssigneeErrors];

export type AppealsUpdateAssigneeResponses = {
    /**
     * Successful Response
     */
    200: AppealOut;
};

export type AppealsUpdateAssigneeResponse = AppealsUpdateAssigneeResponses[keyof AppealsUpdateAssigneeResponses];

export type AppealsListNotesData = {
    body?: never;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/notes';
};

export type AppealsListNotesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsListNotesError = AppealsListNotesErrors[keyof AppealsListNotesErrors];

export type AppealsListNotesResponses = {
    /**
     * Response Appeals List Notes
     *
     * Successful Response
     */
    200: Array<AppealNoteOut>;
};

export type AppealsListNotesResponse = AppealsListNotesResponses[keyof AppealsListNotesResponses];

export type AppealsCreateNoteData = {
    body: AppealNoteCreateIn;
    path: {
        /**
         * Appeal Id
         */
        appeal_id: string;
    };
    query?: never;
    url: '/api/v1/appeals/{appeal_id}/notes';
};

export type AppealsCreateNoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppealsCreateNoteError = AppealsCreateNoteErrors[keyof AppealsCreateNoteErrors];

export type AppealsCreateNoteResponses = {
    /**
     * Successful Response
     */
    201: AppealNoteOut;
};

export type AppealsCreateNoteResponse = AppealsCreateNoteResponses[keyof AppealsCreateNoteResponses];

export type AttendanceMyLessonsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Day
         *
         * Sukut boʻyicha bugun
         */
        day?: string | null;
    };
    url: '/api/v1/attendance/my-lessons';
};

export type AttendanceMyLessonsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AttendanceMyLessonsError = AttendanceMyLessonsErrors[keyof AttendanceMyLessonsErrors];

export type AttendanceMyLessonsResponses = {
    /**
     * Response Attendance My Lessons
     *
     * Successful Response
     */
    200: Array<TeacherLessonOut>;
};

export type AttendanceMyLessonsResponse = AttendanceMyLessonsResponses[keyof AttendanceMyLessonsResponses];

export type AttendanceLessonAttendanceData = {
    body?: never;
    path: {
        /**
         * Lesson Id
         */
        lesson_id: string;
    };
    query?: never;
    url: '/api/v1/attendance/lessons/{lesson_id}';
};

export type AttendanceLessonAttendanceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AttendanceLessonAttendanceError = AttendanceLessonAttendanceErrors[keyof AttendanceLessonAttendanceErrors];

export type AttendanceLessonAttendanceResponses = {
    /**
     * Successful Response
     */
    200: LessonAttendanceOut;
};

export type AttendanceLessonAttendanceResponse = AttendanceLessonAttendanceResponses[keyof AttendanceLessonAttendanceResponses];

export type AttendanceMarkData = {
    body: AttendanceMarkIn;
    path: {
        /**
         * Lesson Id
         */
        lesson_id: string;
    };
    query?: never;
    url: '/api/v1/attendance/lessons/{lesson_id}';
};

export type AttendanceMarkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AttendanceMarkError = AttendanceMarkErrors[keyof AttendanceMarkErrors];

export type AttendanceMarkResponses = {
    /**
     * Successful Response
     */
    200: AttendanceMarkOut;
};

export type AttendanceMarkResponse = AttendanceMarkResponses[keyof AttendanceMarkResponses];

export type AttendanceStatsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Student Id
         */
        student_id?: string | null;
        /**
         * Class Id
         */
        class_id?: string | null;
        /**
         * Subject Id
         */
        subject_id?: string | null;
        /**
         * Teacher Id
         */
        teacher_id?: string | null;
        /**
         * Date From
         */
        date_from?: string | null;
        /**
         * Date To
         */
        date_to?: string | null;
    };
    url: '/api/v1/attendance/stats';
};

export type AttendanceStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AttendanceStatsError = AttendanceStatsErrors[keyof AttendanceStatsErrors];

export type AttendanceStatsResponses = {
    /**
     * Successful Response
     */
    200: AttendanceStatOut;
};

export type AttendanceStatsResponse = AttendanceStatsResponses[keyof AttendanceStatsResponses];

export type AttendanceClassStudentsData = {
    body?: never;
    path: {
        /**
         * Class Id
         */
        class_id: string;
    };
    query?: {
        /**
         * Date From
         */
        date_from?: string | null;
        /**
         * Date To
         */
        date_to?: string | null;
    };
    url: '/api/v1/attendance/classes/{class_id}/students';
};

export type AttendanceClassStudentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AttendanceClassStudentsError = AttendanceClassStudentsErrors[keyof AttendanceClassStudentsErrors];

export type AttendanceClassStudentsResponses = {
    /**
     * Response Attendance Class Students
     *
     * Successful Response
     */
    200: Array<StudentStatOut>;
};

export type AttendanceClassStudentsResponse = AttendanceClassStudentsResponses[keyof AttendanceClassStudentsResponses];

export type ParentMyChildrenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/parent/children';
};

export type ParentMyChildrenResponses = {
    /**
     * Response Parent My Children
     *
     * Successful Response
     */
    200: Array<ChildOut>;
};

export type ParentMyChildrenResponse = ParentMyChildrenResponses[keyof ParentMyChildrenResponses];

export type ParentChildAttendanceData = {
    body?: never;
    path: {
        /**
         * Student Id
         */
        student_id: string;
    };
    query?: {
        /**
         * Date From
         */
        date_from?: string | null;
        /**
         * Date To
         */
        date_to?: string | null;
    };
    url: '/api/v1/parent/children/{student_id}/attendance';
};

export type ParentChildAttendanceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParentChildAttendanceError = ParentChildAttendanceErrors[keyof ParentChildAttendanceErrors];

export type ParentChildAttendanceResponses = {
    /**
     * Response Parent Child Attendance
     *
     * Successful Response
     */
    200: Array<DayAttendanceOut>;
};

export type ParentChildAttendanceResponse = ParentChildAttendanceResponses[keyof ParentChildAttendanceResponses];

export type NotificationsListNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Only Unread
         */
        only_unread?: boolean;
        /**
         * Section
         */
        section?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/notifications';
};

export type NotificationsListNotificationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotificationsListNotificationsError = NotificationsListNotificationsErrors[keyof NotificationsListNotificationsErrors];

export type NotificationsListNotificationsResponses = {
    /**
     * Response Notifications List Notifications
     *
     * Successful Response
     */
    200: Array<NotificationOut>;
};

export type NotificationsListNotificationsResponse = NotificationsListNotificationsResponses[keyof NotificationsListNotificationsResponses];

export type NotificationsBadgesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/badges';
};

export type NotificationsBadgesResponses = {
    /**
     * Successful Response
     */
    200: BadgeOut;
};

export type NotificationsBadgesResponse = NotificationsBadgesResponses[keyof NotificationsBadgesResponses];

export type NotificationsMarkReadData = {
    body: MarkReadIn;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/read';
};

export type NotificationsMarkReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotificationsMarkReadError = NotificationsMarkReadErrors[keyof NotificationsMarkReadErrors];

export type NotificationsMarkReadResponses = {
    /**
     * Successful Response
     */
    200: MarkReadOut;
};

export type NotificationsMarkReadResponse = NotificationsMarkReadResponses[keyof NotificationsMarkReadResponses];

export type NotificationsMarkAllReadData = {
    body: MarkAllReadIn;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/read-all';
};

export type NotificationsMarkAllReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotificationsMarkAllReadError = NotificationsMarkAllReadErrors[keyof NotificationsMarkAllReadErrors];

export type NotificationsMarkAllReadResponses = {
    /**
     * Successful Response
     */
    200: MarkReadOut;
};

export type NotificationsMarkAllReadResponse = NotificationsMarkAllReadResponses[keyof NotificationsMarkAllReadResponses];

export type ServiceHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type ServiceHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthOut;
};

export type ServiceHealthResponse = ServiceHealthResponses[keyof ServiceHealthResponses];

export type ServiceReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ServiceReadinessResponses = {
    /**
     * Successful Response
     */
    200: ReadinessOut;
};

export type ServiceReadinessResponse = ServiceReadinessResponses[keyof ServiceReadinessResponses];
