// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AttendancePoint
 */
export type AttendancePoint = {
    /**
     * Date
     */
    date: string;
    /**
     * Percent
     */
    percent: number;
};

/**
 * ChangePasswordIn
 *
 * Parolni almashtirish (AUT-08).
 *
 * Eski parol soʻraladi — ochiq qolgan sessiyani topgan odam hisobni
 * butunlay egallab olmasin.
 */
export type ChangePasswordIn = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ClassRowOut
 */
export type ClassRowOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Homeroom Teacher Name
     */
    homeroom_teacher_name: string | null;
    /**
     * Student Count
     */
    student_count: number;
    /**
     * Attendance Percent
     */
    attendance_percent: number;
    /**
     * Average Grade
     */
    average_grade: number;
};

/**
 * DirectorOverviewOut
 */
export type DirectorOverviewOut = {
    /**
     * Total Students
     */
    total_students: number;
    /**
     * Total Teachers
     */
    total_teachers: number;
    /**
     * Total Classes
     */
    total_classes: number;
    /**
     * Attendance Percent
     */
    attendance_percent: number;
    /**
     * Average Grade
     */
    average_grade: number;
    /**
     * Lessons Conducted
     */
    lessons_conducted: number;
    /**
     * Attendance Trend
     */
    attendance_trend: Array<AttendancePoint>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthOut
 */
export type HealthOut = {
    /**
     * Status
     */
    status: 'ok';
};

/**
 * LoginIn
 */
export type LoginIn = {
    /**
     * Login
     */
    login: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ReadinessOut
 *
 * Ilova soʻrov qabul qilishga tayyormi.
 *
 * `database` — bazaga soʻrov yuborib tekshiriladi. Ulanish puli boʻsh
 * boʻlsa ham javob beradi: pool_pre_ping yangi ulanish ochadi.
 */
export type ReadinessOut = {
    /**
     * Status
     */
    status: 'ok' | 'degraded';
    /**
     * Database
     */
    database: boolean;
};

/**
 * TeacherRowOut
 */
export type TeacherRowOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Short Name
     */
    short_name: string;
    /**
     * Subjects
     */
    subjects: Array<string>;
    /**
     * Homeroom Class Name
     */
    homeroom_class_name: string | null;
    /**
     * Weekly Hours
     */
    weekly_hours: number;
    /**
     * Lessons Conducted
     */
    lessons_conducted: number;
    /**
     * Average Grade Given
     */
    average_grade_given: number;
    /**
     * Grades Given
     */
    grades_given: number;
};

/**
 * TokenOut
 *
 * Refresh token javob tanasida QAYTMAYDI — httpOnly cookie'da ketadi.
 */
export type TokenOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    user: UserOut;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Login
     */
    login: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Short Name
     */
    short_name: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Must Change Password
     */
    must_change_password: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthLoginData = {
    body: LoginIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenOut;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthRefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenOut;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthMeResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthChangePasswordData = {
    body: ChangePasswordIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password';
};

export type AuthChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthChangePasswordError = AuthChangePasswordErrors[keyof AuthChangePasswordErrors];

export type AuthChangePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthChangePasswordResponse = AuthChangePasswordResponses[keyof AuthChangePasswordResponses];

export type DirectorOverviewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         *
         * Necha kunlik davr
         */
        days?: number;
    };
    url: '/api/v1/director/overview';
};

export type DirectorOverviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DirectorOverviewError = DirectorOverviewErrors[keyof DirectorOverviewErrors];

export type DirectorOverviewResponses = {
    /**
     * Successful Response
     */
    200: DirectorOverviewOut;
};

export type DirectorOverviewResponse = DirectorOverviewResponses[keyof DirectorOverviewResponses];

export type DirectorClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/director/classes';
};

export type DirectorClassesResponses = {
    /**
     * Response Director Classes
     *
     * Successful Response
     */
    200: Array<ClassRowOut>;
};

export type DirectorClassesResponse = DirectorClassesResponses[keyof DirectorClassesResponses];

export type DirectorTeachersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/director/teachers';
};

export type DirectorTeachersResponses = {
    /**
     * Response Director Teachers
     *
     * Successful Response
     */
    200: Array<TeacherRowOut>;
};

export type DirectorTeachersResponse = DirectorTeachersResponses[keyof DirectorTeachersResponses];

export type ServiceHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type ServiceHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthOut;
};

export type ServiceHealthResponse = ServiceHealthResponses[keyof ServiceHealthResponses];

export type ServiceReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ServiceReadinessResponses = {
    /**
     * Successful Response
     */
    200: ReadinessOut;
};

export type ServiceReadinessResponse = ServiceReadinessResponses[keyof ServiceReadinessResponses];
