"""X-14 ikki bosqichli tasdiqlash

Revision ID: 6608eef4758f
Revises: 762b31f06227
Create Date: 2026-08-31 15:33:14.712224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6608eef4758f'
down_revision: Union[str, Sequence[str], None] = '762b31f06227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_factor_recovery_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_ip', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_two_factor_recovery_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_two_factor_recovery_codes'))
    )
    op.create_index('ix_2fa_recovery_user', 'two_factor_recovery_codes', ['user_id', 'used_at'], unique=False)
    op.create_index(op.f('ix_two_factor_recovery_codes_code_hash'), 'two_factor_recovery_codes', ['code_hash'], unique=False)
    op.create_index(op.f('ix_two_factor_recovery_codes_is_archived'), 'two_factor_recovery_codes', ['is_archived'], unique=False)
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('totp_enabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('totp_last_step', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_last_step')
    op.drop_column('users', 'totp_enabled_at')
    op.drop_column('users', 'totp_secret')
    op.drop_index(op.f('ix_two_factor_recovery_codes_is_archived'), table_name='two_factor_recovery_codes')
    op.drop_index(op.f('ix_two_factor_recovery_codes_code_hash'), table_name='two_factor_recovery_codes')
    op.drop_index('ix_2fa_recovery_user', table_name='two_factor_recovery_codes')
    op.drop_table('two_factor_recovery_codes')
    # ### end Alembic commands ###
