"""T-037 — sababli qoldirish arizasi (DAV-04).

Vasiy ariza yozadi (matn va fayl), sinf rahbari tasdiqlaydi yoki rad
etadi. Tasdiqlanganda oʻsha kunlardagi darslar «sababli» ga oʻtadi.

Ariza oʻchirilmaydi va tahrirlanmaydi — u davomat oʻzgarishining
asosi. «Nega bu kun sababli boʻlib qoldi» savoliga javob shu jadvalda.

Revision ID: 08051aaf3468
Revises: 6d0b44434ad3
Create Date: 2026-09-05 10:03:52.673832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08051aaf3468'
down_revision: Union[str, Sequence[str], None] = '6d0b44434ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_requests',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='kutilmoqda', nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('marked_lessons', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_absence_requests_created_by_id_users')),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_absence_requests_decided_by_id_users')),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], name=op.f('fk_absence_requests_file_id_stored_files')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_absence_requests_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_absence_requests'))
    )
    op.create_index(op.f('ix_absence_requests_is_archived'), 'absence_requests', ['is_archived'], unique=False)
    op.create_index('ix_absence_status', 'absence_requests', ['status', 'created_at'], unique=False)
    op.create_index('ix_absence_student_range', 'absence_requests', ['student_id', 'date_from', 'date_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_absence_student_range', table_name='absence_requests')
    op.drop_index('ix_absence_status', table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_is_archived'), table_name='absence_requests')
    op.drop_table('absence_requests')
    # ### end Alembic commands ###
