"""T-031 — chorak bahosi (JUR-04).

`term_grades`: chorak bahosi vaznlar boʻyicha hisoblanadi va YAKUNLANADI.
Saqlanishining sababi — yakunlangandan keyin u hujjat: keyin eski
darsning bahosi tuzatilsa, chorak bahosi oʻz-oʻzidan siljib ketmasin.

`computed_value` yonida turadi, chunki "avtomatik nechchi chiqqan edi"
savoliga javob kerak. Qoʻlda tuzatishda `reason` majburiy (JUR-04).

Revision ID: ce23f30e5be0
Revises: a56d08601550
Create Date: 2026-09-05 09:36:57.155496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce23f30e5be0'
down_revision: Union[str, Sequence[str], None] = 'a56d08601550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_grades',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('computed_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), server_default='5', nullable=False),
    sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('set_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('value >= 0', name=op.f('ck_term_grades_term_grade_non_negative')),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], name=op.f('fk_term_grades_set_by_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_term_grades_student_id_students')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_term_grades_subject_id_subjects')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_term_grades_term_id_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term_grades'))
    )
    op.create_index(op.f('ix_term_grades_is_archived'), 'term_grades', ['is_archived'], unique=False)
    op.create_index('uq_term_grade', 'term_grades', ['student_id', 'subject_id', 'term_id'], unique=True, postgresql_where=sa.text('NOT is_archived'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_term_grade', table_name='term_grades', postgresql_where=sa.text('NOT is_archived'))
    op.drop_index(op.f('ix_term_grades_is_archived'), table_name='term_grades')
    op.drop_table('term_grades')
    # ### end Alembic commands ###
