"""kadrlar profillari va tatillar

Revision ID: 9bbbabff8b56
Revises: 71aabf2757ae
Create Date: 2026-09-01 16:44:17.374708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bbbabff8b56'
down_revision: Union[str, Sequence[str], None] = '71aabf2757ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_leaves',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_leaves_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_leaves'))
    )
    op.create_index(op.f('ix_staff_leaves_is_archived'), 'staff_leaves', ['is_archived'], unique=False)
    op.create_index('ix_staff_leaves_user', 'staff_leaves', ['user_id', 'starts_on'], unique=False)
    op.create_table('staff_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=80), nullable=False),
    sa.Column('contract_type', sa.String(length=16), nullable=False),
    sa.Column('qualification', sa.String(length=16), nullable=False),
    sa.Column('hired_on', sa.Date(), nullable=True),
    sa.Column('base_salary', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_staff_profiles_user_id'))
    )
    op.create_index(op.f('ix_staff_profiles_is_archived'), 'staff_profiles', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_profiles_is_archived'), table_name='staff_profiles')
    op.drop_table('staff_profiles')
    op.drop_index('ix_staff_leaves_user', table_name='staff_leaves')
    op.drop_index(op.f('ix_staff_leaves_is_archived'), table_name='staff_leaves')
    op.drop_table('staff_leaves')
    # ### end Alembic commands ###
