"""imtihonlar va dars rejalari

Revision ID: 492725d06460
Revises: 9bbbabff8b56
Create Date: 2026-09-01 16:52:59.107448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492725d06460'
down_revision: Union[str, Sequence[str], None] = '9bbbabff8b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_exams_class_id_classes')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_exams_created_by_id_users')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_exams_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    op.create_index('ix_exams_date', 'exams', ['exam_date'], unique=False)
    op.create_index(op.f('ix_exams_is_archived'), 'exams', ['is_archived'], unique=False)
    op.create_table('lesson_plans',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_lesson_plans_class_id_classes')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lesson_plans_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_lesson_plans_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_plans')),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'class_id', 'period', name=op.f('uq_lesson_plans_teacher_id_subject_id_class_id_period'))
    )
    op.create_index(op.f('ix_lesson_plans_is_archived'), 'lesson_plans', ['is_archived'], unique=False)
    op.create_index(op.f('ix_lesson_plans_teacher_id'), 'lesson_plans', ['teacher_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('absent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_results_exam_id_exams')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_exam_results_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_results')),
    sa.UniqueConstraint('exam_id', 'student_id', name=op.f('uq_exam_results_exam_id_student_id'))
    )
    op.create_index(op.f('ix_exam_results_exam_id'), 'exam_results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_results_is_archived'), 'exam_results', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_results_is_archived'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_exam_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_lesson_plans_teacher_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_is_archived'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    op.drop_index(op.f('ix_exams_is_archived'), table_name='exams')
    op.drop_index('ix_exams_date', table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
