"""tolov kredit yozuvlari

Revision ID: 08c0dcdc3cfe
Revises: bf634d2b4c24
Create Date: 2026-09-01 17:56:46.159795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c0dcdc3cfe'
down_revision: Union[str, Sequence[str], None] = 'bf634d2b4c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuition_credits',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tuition_credits_created_by_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_tuition_credits_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tuition_credits'))
    )
    op.create_index(op.f('ix_tuition_credits_is_archived'), 'tuition_credits', ['is_archived'], unique=False)
    op.create_index('ix_tuition_credits_student', 'tuition_credits', ['student_id', 'is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tuition_credits_student', table_name='tuition_credits')
    op.drop_index(op.f('ix_tuition_credits_is_archived'), table_name='tuition_credits')
    op.drop_table('tuition_credits')
    # ### end Alembic commands ###
