"""t003 login huquqlar rollar

Revision ID: 775e4a7f74a0
Revises: fbc3e623399b
Create Date: 2026-08-30 22:30:45.283920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775e4a7f74a0'
down_revision: Union[str, Sequence[str], None] = 'fbc3e623399b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=64), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_user_permissions_granted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permissions'))
    )
    op.create_index(op.f('ix_user_permissions_is_archived'), 'user_permissions', ['is_archived'], unique=False)
    op.create_index('ix_user_permissions_lookup', 'user_permissions', ['user_id', 'permission', 'is_archived'], unique=False)
    op.add_column("login_attempts", sa.Column("login", sa.String(length=64), nullable=True))
    op.execute("UPDATE login_attempts SET login = coalesce(phone, '') WHERE login IS NULL")
    op.alter_column("login_attempts", "login", nullable=False)
    op.drop_index(op.f('ix_login_attempts_phone_time'), table_name='login_attempts')
    op.create_index('ix_login_attempts_login_time', 'login_attempts', ['login', 'created_at'], unique=False)
    op.drop_column('login_attempts', 'phone')
    # Mavjud qatorlar boʻlsa NOT NULL qoʻshib boʻlmaydi. Hozir jadval
    # boʻsh, lekin migratsiya har qanday holatda ishlashi kerak: avval
    # nullable qoʻshiladi, id dan vaqtinchalik login yasaladi, keyin
    # NOT NULL qilinadi.
    op.add_column("users", sa.Column("login", sa.String(length=64), nullable=True))
    # TUZATILDI: avval `left(id::text, 8)` edi va toʻldirish `ix_users_login`
    # unique indeksida yiqilardi. Sabab — kalitlar UUIDv7: birinchi 8 belgi
    # VAQT belgisi, bir seansda yaratilgan 362 ta oʻquvchi vasiysi uchun u
    # bir xil chiqadi ("user01a053c1" ikki marta). Boʻsh bazada bilinmaydi,
    # maʼlumot bor bazada migratsiya butunlay oʻtmaydi. Toʻliq id olinadi:
    # 4 + 32 = 36 belgi, `String(64)` ga sigʻadi va takrorlanmaydi.
    op.execute(
        "UPDATE users SET login = 'user' || replace(id::text, '-', '') WHERE login IS NULL"
    )
    op.alter_column("users", "login", nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###

    # --- Rollar maʼlumotnomasi (AUT-04) ---
    #
    # UUID lar QATʼIY yozilgan, generatsiya qilinmagan: rol identifikatori
    # dev, test va ishlab chiqarishda bir xil boʻlishi kerak. Aks holda
    # bir muhitdan olingan `user_roles` yozuvi boshqasida boshqa rolni
    # koʻrsatardi.
    #
    # Rollar hech qachon oʻchirilmaydi — `roles` da `is_archived` ham yoʻq.
    # TUZATILDI: avval `op.bulk_insert` edi va rollar allaqachon mavjud
    # bazada `uq_roles_name` da yiqilardi (eski seed `ensure_roles()` ularni
    # yaratib qoʻygan boʻlishi mumkin). Migratsiya har qanday boshlangʻich
    # holatda oʻtishi kerak, shuning uchun `ON CONFLICT DO NOTHING`.
    #
    # Mavjud qatorning id'si SAQLANADI — qayta yozilsa unga bogʻlangan
    # `user_roles` yozuvlari yetim qolardi. Yangi muhitda esa id'lar shu
    # yerdagi qatʼiy qiymatlar boʻladi.
    op.execute(
        """
        INSERT INTO roles (id, name, description) VALUES
        ('0193b000-0000-7000-8000-000000000001', 'student', 'Oʻquvchi'),
        ('0193b000-0000-7000-8000-000000000002', 'parent', 'Ota-ona (vasiy)'),
        ('0193b000-0000-7000-8000-000000000003', 'teacher', 'Ustoz'),
        ('0193b000-0000-7000-8000-000000000004', 'homeroom_teacher', 'Sinf rahbari'),
        ('0193b000-0000-7000-8000-000000000005', 'academic', 'Oʻquv boʻlimi'),
        ('0193b000-0000-7000-8000-000000000006', 'admin', 'Administrator'),
        ('0193b000-0000-7000-8000-000000000007', 'director', 'Rahbariyat'),
        ('0193b000-0000-7000-8000-000000000008', 'superadmin', 'Super administrator')
        ON CONFLICT (name) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM roles WHERE name = 'academic'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'login')
    op.add_column('login_attempts', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index('ix_login_attempts_login_time', table_name='login_attempts')
    op.create_index(op.f('ix_login_attempts_phone_time'), 'login_attempts', ['phone', 'created_at'], unique=False)
    op.drop_column('login_attempts', 'login')
    op.drop_index('ix_user_permissions_lookup', table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_is_archived'), table_name='user_permissions')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
