"""murojaatlar: appeals, appeal_messages, appeal_notes

Revision ID: bc349553ee61
Revises: fbc3e623399b
Create Date: 2026-08-30 22:18:43.458336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc349553ee61'
down_revision: str | None = '775e4a7f74a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_appeals_assignee_id_users')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_appeals_author_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_appeals_student_id_students')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_appeals_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeals'))
    )
    op.create_index('ix_appeals_assignee_status', 'appeals', ['assignee_id', 'status'], unique=False)
    op.create_index('ix_appeals_author_activity', 'appeals', ['author_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_appeals_author_id'), 'appeals', ['author_id'], unique=False)
    op.create_index(op.f('ix_appeals_is_archived'), 'appeals', ['is_archived'], unique=False)
    op.create_index(op.f('ix_appeals_last_message_at'), 'appeals', ['last_message_at'], unique=False)
    op.create_index('ix_appeals_status_due', 'appeals', ['status', 'due_at'], unique=False)
    op.create_index(op.f('ix_appeals_student_id'), 'appeals', ['student_id'], unique=False)
    op.create_table('appeal_messages',
    sa.Column('appeal_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appeal_id'], ['appeals.id'], name=op.f('fk_appeal_messages_appeal_id_appeals')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_appeal_messages_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeal_messages'))
    )
    op.create_index(op.f('ix_appeal_messages_author_id'), 'appeal_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_appeal_messages_is_archived'), 'appeal_messages', ['is_archived'], unique=False)
    op.create_index('ix_appeal_messages_thread', 'appeal_messages', ['appeal_id', 'created_at'], unique=False)
    op.create_table('appeal_notes',
    sa.Column('appeal_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appeal_id'], ['appeals.id'], name=op.f('fk_appeal_notes_appeal_id_appeals')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_appeal_notes_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeal_notes'))
    )
    op.create_index(op.f('ix_appeal_notes_author_id'), 'appeal_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_appeal_notes_is_archived'), 'appeal_notes', ['is_archived'], unique=False)
    op.create_index('ix_appeal_notes_thread', 'appeal_notes', ['appeal_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appeal_notes_thread', table_name='appeal_notes')
    op.drop_index(op.f('ix_appeal_notes_is_archived'), table_name='appeal_notes')
    op.drop_index(op.f('ix_appeal_notes_author_id'), table_name='appeal_notes')
    op.drop_table('appeal_notes')
    op.drop_index('ix_appeal_messages_thread', table_name='appeal_messages')
    op.drop_index(op.f('ix_appeal_messages_is_archived'), table_name='appeal_messages')
    op.drop_index(op.f('ix_appeal_messages_author_id'), table_name='appeal_messages')
    op.drop_table('appeal_messages')
    op.drop_index(op.f('ix_appeals_student_id'), table_name='appeals')
    op.drop_index('ix_appeals_status_due', table_name='appeals')
    op.drop_index(op.f('ix_appeals_last_message_at'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_is_archived'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_author_id'), table_name='appeals')
    op.drop_index('ix_appeals_author_activity', table_name='appeals')
    op.drop_index('ix_appeals_assignee_status', table_name='appeals')
    op.drop_table('appeals')
    # ### end Alembic commands ###
