"""telegram bogʻlash kodlari (T-017, BOT-01)

Revision ID: efda620f7891
Revises: e400466c242d
Create Date: 2026-09-02 20:18:41.505411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efda620f7891'
down_revision: Union[str, Sequence[str], None] = 'e400466c242d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_link_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_link_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_link_codes'))
    )
    op.create_index(op.f('ix_telegram_link_codes_is_archived'), 'telegram_link_codes', ['is_archived'], unique=False)
    op.create_index('ix_tg_link_user', 'telegram_link_codes', ['user_id', 'used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tg_link_user', table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_is_archived'), table_name='telegram_link_codes')
    op.drop_table('telegram_link_codes')
    # ### end Alembic commands ###
