"""xabar shablonlari va davomat kechikishi (T-019, BOT-05, DAV-05)

Revision ID: bf3e5898befd
Revises: efda620f7891
Create Date: 2026-09-03 09:09:32.978587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf3e5898befd'
down_revision: Union[str, Sequence[str], None] = 'efda620f7891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_message_templates_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_templates')),
    sa.UniqueConstraint('kind', name=op.f('uq_message_templates_kind'))
    )
    op.create_index(op.f('ix_message_templates_is_archived'), 'message_templates', ['is_archived'], unique=False)
    op.add_column('school_settings', sa.Column('attendance_notify_delay_minutes', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_settings', 'attendance_notify_delay_minutes')
    op.drop_index(op.f('ix_message_templates_is_archived'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
