"""malumotnomalar reyestri

Revision ID: 3097b776ce50
Revises: f46e6d391e93
Create Date: 2026-09-01 16:25:28.433170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3097b776ce50'
down_revision: Union[str, Sequence[str], None] = 'f46e6d391e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_requests',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by_id', sa.UUID(), nullable=True),
    sa.Column('recipient', sa.String(length=200), nullable=True),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('extra_text', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_document_requests_issued_by_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_document_requests_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_requests')),
    sa.UniqueConstraint('number', name=op.f('uq_document_requests_number'))
    )
    op.create_index(op.f('ix_document_requests_is_archived'), 'document_requests', ['is_archived'], unique=False)
    op.create_index('ix_document_requests_status', 'document_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_requests_student_id'), 'document_requests', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_requests_student_id'), table_name='document_requests')
    op.drop_index('ix_document_requests_status', table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_is_archived'), table_name='document_requests')
    op.drop_table('document_requests')
    # ### end Alembic commands ###
