"""T-039 — jadval istisnolari (ADM-10).

Muayyan sanaga: dars bekor qilinishi, ustozni vaqtincha almashtirish,
darsni boshqa paraga koʻchirish.

Alohida jadval yaratilmadi — istisno KONKRET darsga tegishli va
`lessons` ning oʻzi allaqachon sana boʻyicha yozuv. Bekor qilingan
dars arxivlanmaydi: arxivlangani slotni boʻshatadi va keyingi
generatsiya darsni qayta yaratardi.

Revision ID: a2c5106fab2f
Revises: 08051aaf3468
Create Date: 2026-09-05 10:14:39.290568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c5106fab2f'
down_revision: Union[str, Sequence[str], None] = '08051aaf3468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('cancel_reason', sa.String(length=300), nullable=True))
    op.add_column('lessons', sa.Column('is_substituted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('lessons', sa.Column('exception_note', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'exception_note')
    op.drop_column('lessons', 'is_substituted')
    op.drop_column('lessons', 'cancel_reason')
    op.drop_column('lessons', 'cancelled_at')
    # ### end Alembic commands ###
