"""T-025 — fayl saqlash (MET-03, NFR-11).

`stored_files`: faqat metamaʼlumot. Baytlar diskda
(`settings.file_storage_dir`), bazada esa kalit — CLAUDE.md 10-qoida.

Cloudflare R2 emas, serverning oʻz diski: egasining qarori
(5-sentabr 2026). Maʼlumot Oʻzbekistonda qoladi va mavjud zaxira
skriptiga qoʻshiladi.

Revision ID: 6d0b44434ad3
Revises: ce23f30e5be0
Create Date: 2026-09-05 09:55:36.982707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0b44434ad3'
down_revision: Union[str, Sequence[str], None] = 'ce23f30e5be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_files',
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_stored_files_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_stored_files_storage_key'))
    )
    op.create_index(op.f('ix_stored_files_is_archived'), 'stored_files', ['is_archived'], unique=False)
    op.create_index('ix_stored_files_owner', 'stored_files', ['uploaded_by_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stored_files_owner', table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_is_archived'), table_name='stored_files')
    op.drop_table('stored_files')
    # ### end Alembic commands ###
