"""t002 boshlangich sxema

Revision ID: fbc3e623399b
Revises: 
Create Date: 2026-08-30 18:10:17.252646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbc3e623399b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ends_on > starts_on', name=op.f('ck_academic_years_year_dates_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years'))
    )
    op.create_index(op.f('ix_academic_years_is_archived'), 'academic_years', ['is_archived'], unique=False)
    op.create_index('uq_academic_years_single_current', 'academic_years', ['is_current'], unique=True, postgresql_where='is_current')
    op.create_table('login_attempts',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_phone_time', 'login_attempts', ['phone', 'created_at'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('subjects',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('name', name=op.f('uq_subjects_name'))
    )
    op.create_index(op.f('ix_subjects_is_archived'), 'subjects', ['is_archived'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_is_archived'), 'users', ['is_archived'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_actor', 'audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_object', 'audit_log', ['object_type', 'object_id', 'created_at'], unique=False)
    op.create_table('bell_schedule',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_bell_schedule_bell_times_ordered')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_bell_schedule_academic_year_id_academic_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bell_schedule')),
    sa.UniqueConstraint('academic_year_id', 'period', name=op.f('uq_bell_schedule_academic_year_id_period'))
    )
    op.create_index(op.f('ix_bell_schedule_is_archived'), 'bell_schedule', ['is_archived'], unique=False)
    op.create_table('classes',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('homeroom_teacher_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_classes_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['users.id'], name=op.f('fk_classes_homeroom_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    sa.UniqueConstraint('academic_year_id', 'name', name=op.f('uq_classes_academic_year_id_name'))
    )
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_classes_homeroom_teacher_id'), 'classes', ['homeroom_teacher_id'], unique=False)
    op.create_index(op.f('ix_classes_is_archived'), 'classes', ['is_archived'], unique=False)
    op.create_table('holidays',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_holidays_academic_year_id_academic_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('academic_year_id', 'day', name=op.f('uq_holidays_academic_year_id_day'))
    )
    op.create_index(op.f('ix_holidays_day'), 'holidays', ['day'], unique=False)
    op.create_index(op.f('ix_holidays_is_archived'), 'holidays', ['is_archived'], unique=False)
    op.create_table('login_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_log'))
    )
    op.create_index('ix_login_log_user_time', 'login_log', ['user_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teacher_subjects_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teacher_subjects_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_subjects')),
    sa.UniqueConstraint('teacher_id', 'subject_id', name=op.f('uq_teacher_subjects_teacher_id_subject_id'))
    )
    op.create_index(op.f('ix_teacher_subjects_is_archived'), 'teacher_subjects', ['is_archived'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_teacher_id'), 'teacher_subjects', ['teacher_id'], unique=False)
    op.create_table('terms',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ends_on > starts_on', name=op.f('ck_terms_term_dates_ordered')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_terms_academic_year_id_academic_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms')),
    sa.UniqueConstraint('academic_year_id', 'index', name=op.f('uq_terms_academic_year_id_index'))
    )
    op.create_index(op.f('ix_terms_is_archived'), 'terms', ['is_archived'], unique=False)
    op.create_index('ix_terms_year_range', 'terms', ['academic_year_id', 'starts_on', 'ends_on'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('class_subjects',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_subjects_class_id_classes')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_class_subjects_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_subjects')),
    sa.UniqueConstraint('class_id', 'subject_id', name=op.f('uq_class_subjects_class_id_subject_id'))
    )
    op.create_index(op.f('ix_class_subjects_is_archived'), 'class_subjects', ['is_archived'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('period BETWEEN 1 AND 10', name=op.f('ck_schedule_entries_period_range')),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name=op.f('ck_schedule_entries_weekday_range')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_schedule_entries_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_schedule_entries_class_id_classes')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_schedule_entries_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_schedule_entries_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_entries'))
    )
    op.create_index(op.f('ix_schedule_entries_is_archived'), 'schedule_entries', ['is_archived'], unique=False)
    op.create_index(op.f('ix_schedule_entries_teacher_id'), 'schedule_entries', ['teacher_id'], unique=False)
    op.create_index('uq_schedule_class_slot', 'schedule_entries', ['academic_year_id', 'weekday', 'period', 'class_id'], unique=True, postgresql_where='NOT is_archived')
    op.create_index('uq_schedule_room_slot', 'schedule_entries', ['academic_year_id', 'weekday', 'period', 'room'], unique=True, postgresql_where='NOT is_archived AND room IS NOT NULL')
    op.create_index('uq_schedule_teacher_slot', 'schedule_entries', ['academic_year_id', 'weekday', 'period', 'teacher_id'], unique=True, postgresql_where='NOT is_archived')
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_students_class_id_classes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('user_id', name=op.f('uq_students_user_id'))
    )
    op.create_index('ix_students_class_active', 'students', ['class_id', 'is_archived'], unique=False)
    op.create_index('ix_students_identity', 'students', ['last_name', 'first_name', 'birth_date'], unique=False)
    op.create_index(op.f('ix_students_is_archived'), 'students', ['is_archived'], unique=False)
    op.create_table('guardians',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_guardians_student_id_students')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_guardians_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardians')),
    sa.UniqueConstraint('student_id', 'user_id', name=op.f('uq_guardians_student_id_user_id'))
    )
    op.create_index(op.f('ix_guardians_is_archived'), 'guardians', ['is_archived'], unique=False)
    op.create_index('ix_guardians_user', 'guardians', ['user_id', 'is_archived'], unique=False)
    op.create_table('lessons',
    sa.Column('schedule_entry_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=30), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('attendance_marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_lessons_class_id_classes')),
    sa.ForeignKeyConstraint(['schedule_entry_id'], ['schedule_entries.id'], name=op.f('fk_lessons_schedule_entry_id_schedule_entries')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lessons_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_lessons_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('class_id', 'lesson_date', 'period', name=op.f('uq_lessons_class_id_lesson_date_period'))
    )
    op.create_index('ix_lessons_class_date', 'lessons', ['class_id', 'lesson_date'], unique=False)
    op.create_index(op.f('ix_lessons_is_archived'), 'lessons', ['is_archived'], unique=False)
    op.create_index('ix_lessons_teacher_date', 'lessons', ['teacher_id', 'lesson_date'], unique=False)
    op.create_table('attendance_records',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('marked_by_id', sa.UUID(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_attendance_records_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['marked_by_id'], ['users.id'], name=op.f('fk_attendance_records_marked_by_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_records_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('lesson_id', 'student_id', name=op.f('uq_attendance_records_lesson_id_student_id'))
    )
    op.create_index('ix_attendance_lesson', 'attendance_records', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_is_archived'), 'attendance_records', ['is_archived'], unique=False)
    op.create_index('ix_attendance_student_status', 'attendance_records', ['student_id', 'status'], unique=False)
    op.create_table('homework',
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allow_late', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('grading_scale', sa.String(length=10), server_default='five', nullable=False),
    sa.Column('max_score', sa.Integer(), server_default='5', nullable=False),
    sa.Column('weight', sa.Integer(), server_default='1', nullable=False),
    sa.Column('attachment_key', sa.String(length=300), nullable=True),
    sa.Column('attachment_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_homework_class_id_classes')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_homework_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_homework_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_homework_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homework'))
    )
    op.create_index('ix_homework_class_due', 'homework', ['class_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_homework_is_archived'), 'homework', ['is_archived'], unique=False)
    op.create_index('ix_homework_teacher_due', 'homework', ['teacher_id', 'due_at'], unique=False)
    op.create_table('homework_submissions',
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='assigned', nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('attachment_key', sa.String(length=300), nullable=True),
    sa.Column('attachment_name', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('graded_by_id', sa.UUID(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score IS NULL OR score >= 0', name=op.f('ck_homework_submissions_score_non_negative')),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.id'], name=op.f('fk_homework_submissions_graded_by_id_users')),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], name=op.f('fk_homework_submissions_homework_id_homework')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_homework_submissions_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homework_submissions')),
    sa.UniqueConstraint('homework_id', 'student_id', name=op.f('uq_homework_submissions_homework_id_student_id'))
    )
    op.create_index(op.f('ix_homework_submissions_is_archived'), 'homework_submissions', ['is_archived'], unique=False)
    op.create_index('ix_submissions_status_time', 'homework_submissions', ['status', 'submitted_at'], unique=False)
    op.create_index('ix_submissions_student', 'homework_submissions', ['student_id', 'status'], unique=False)
    op.create_table('grades',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='current', nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('max_value', sa.Integer(), server_default='5', nullable=False),
    sa.Column('weight', sa.Integer(), server_default='1', nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('value >= 0', name=op.f('ck_grades_grade_non_negative')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_grades_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_grades_student_id_students')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_grades_subject_id_subjects')),
    sa.ForeignKeyConstraint(['submission_id'], ['homework_submissions.id'], name=op.f('fk_grades_submission_id_homework_submissions')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_grades_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('submission_id', name=op.f('uq_grades_submission_id'))
    )
    op.create_index(op.f('ix_grades_is_archived'), 'grades', ['is_archived'], unique=False)
    op.create_index('ix_grades_lesson', 'grades', ['lesson_id'], unique=False)
    op.create_index('ix_grades_student_subject', 'grades', ['student_id', 'subject_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_grades_student_subject', table_name='grades')
    op.drop_index('ix_grades_lesson', table_name='grades')
    op.drop_index(op.f('ix_grades_is_archived'), table_name='grades')
    op.drop_table('grades')
    op.drop_index('ix_submissions_student', table_name='homework_submissions')
    op.drop_index('ix_submissions_status_time', table_name='homework_submissions')
    op.drop_index(op.f('ix_homework_submissions_is_archived'), table_name='homework_submissions')
    op.drop_table('homework_submissions')
    op.drop_index('ix_homework_teacher_due', table_name='homework')
    op.drop_index(op.f('ix_homework_is_archived'), table_name='homework')
    op.drop_index('ix_homework_class_due', table_name='homework')
    op.drop_table('homework')
    op.drop_index('ix_attendance_student_status', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_is_archived'), table_name='attendance_records')
    op.drop_index('ix_attendance_lesson', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_lessons_teacher_date', table_name='lessons')
    op.drop_index(op.f('ix_lessons_is_archived'), table_name='lessons')
    op.drop_index('ix_lessons_class_date', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_guardians_user', table_name='guardians')
    op.drop_index(op.f('ix_guardians_is_archived'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_students_is_archived'), table_name='students')
    op.drop_index('ix_students_identity', table_name='students')
    op.drop_index('ix_students_class_active', table_name='students')
    op.drop_table('students')
    op.drop_index('uq_schedule_teacher_slot', table_name='schedule_entries', postgresql_where='NOT is_archived')
    op.drop_index('uq_schedule_room_slot', table_name='schedule_entries', postgresql_where='NOT is_archived AND room IS NOT NULL')
    op.drop_index('uq_schedule_class_slot', table_name='schedule_entries', postgresql_where='NOT is_archived')
    op.drop_index(op.f('ix_schedule_entries_teacher_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_is_archived'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_class_subjects_is_archived'), table_name='class_subjects')
    op.drop_table('class_subjects')
    op.drop_table('user_roles')
    op.drop_index('ix_terms_year_range', table_name='terms')
    op.drop_index(op.f('ix_terms_is_archived'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_teacher_subjects_teacher_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_is_archived'), table_name='teacher_subjects')
    op.drop_table('teacher_subjects')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_login_log_user_time', table_name='login_log')
    op.drop_table('login_log')
    op.drop_index(op.f('ix_holidays_is_archived'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_day'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_classes_is_archived'), table_name='classes')
    op.drop_index(op.f('ix_classes_homeroom_teacher_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_bell_schedule_is_archived'), table_name='bell_schedule')
    op.drop_table('bell_schedule')
    op.drop_index('ix_audit_object', table_name='audit_log')
    op.drop_index('ix_audit_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_archived'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_is_archived'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('roles')
    op.drop_index('ix_login_attempts_phone_time', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index('uq_academic_years_single_current', table_name='academic_years', postgresql_where='is_current')
    op.drop_index(op.f('ix_academic_years_is_archived'), table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
