"""t009 oquvchi va vasiy kartochkasi maydonlari

Revision ID: 14f922ece868
Revises: 68f2aa8eb753
Create Date: 2026-09-04 07:15:20.549814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f922ece868'
down_revision: Union[str, Sequence[str], None] = '68f2aa8eb753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('previous_school', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('profession', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profession')
    op.drop_column('users', 'address')
    op.drop_column('students', 'previous_school')
    # ### end Alembic commands ###
