"""murojaatni maktab boshlashi: created_by_id

Revision ID: b38ccee68e60
Revises: 4dd12fea2cb6
Create Date: 2026-08-31 07:57:08.704541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38ccee68e60'
down_revision: Union[str, Sequence[str], None] = '4dd12fea2cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_appeals_created_by_id_users'), 'appeals', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_appeals_created_by_id_users'), 'appeals', type_='foreignkey')
    op.drop_column('appeals', 'created_by_id')
    # ### end Alembic commands ###
