"""murojaat qaydiga ustoz baholash maydonlari

Revision ID: 469bc6adbc99
Revises: bc349553ee61
Create Date: 2026-08-30 22:34:47.125355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469bc6adbc99'
down_revision: Union[str, Sequence[str], None] = 'bc349553ee61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeal_notes', sa.Column('about_teacher_id', sa.UUID(), nullable=True))
    op.add_column('appeal_notes', sa.Column('teacher_rating', sa.Integer(), nullable=True))
    op.add_column('appeal_notes', sa.Column('teacher_comment', sa.Text(), nullable=True))
    op.create_index(op.f('ix_appeal_notes_about_teacher_id'), 'appeal_notes', ['about_teacher_id'], unique=False)
    op.create_foreign_key(op.f('fk_appeal_notes_about_teacher_id_users'), 'appeal_notes', 'users', ['about_teacher_id'], ['id'])
    op.create_check_constraint(op.f('ck_appeal_notes_teacher_rating_range'), 'appeal_notes', 'teacher_rating IS NULL OR teacher_rating BETWEEN 1 AND 5')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_appeal_notes_teacher_rating_range'), 'appeal_notes', type_='check')
    op.drop_constraint(op.f('fk_appeal_notes_about_teacher_id_users'), 'appeal_notes', type_='foreignkey')
    op.drop_index(op.f('ix_appeal_notes_about_teacher_id'), table_name='appeal_notes')
    op.drop_column('appeal_notes', 'teacher_comment')
    op.drop_column('appeal_notes', 'teacher_rating')
    op.drop_column('appeal_notes', 'about_teacher_id')
    # ### end Alembic commands ###
