"""tarbiya psixologiya qaydlari

Revision ID: f46e6d391e93
Revises: 6a051cfaee00
Create Date: 2026-09-01 16:17:26.997935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46e6d391e93'
down_revision: Union[str, Sequence[str], None] = '6a051cfaee00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellbeing_notes',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_wellbeing_notes_author_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_wellbeing_notes_student_id_students')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_wellbeing_notes_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wellbeing_notes'))
    )
    op.create_index(op.f('ix_wellbeing_notes_is_archived'), 'wellbeing_notes', ['is_archived'], unique=False)
    op.create_index('ix_wellbeing_student_created', 'wellbeing_notes', ['student_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wellbeing_student_created', table_name='wellbeing_notes')
    op.drop_index(op.f('ix_wellbeing_notes_is_archived'), table_name='wellbeing_notes')
    op.drop_table('wellbeing_notes')
    # ### end Alembic commands ###
