"""T-041..T-043 testlar

Revision ID: 410e951efdfc
Revises: 7b95c064e326
Create Date: 2026-08-31 13:30:25.603018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '410e951efdfc'
down_revision: Union[str, Sequence[str], None] = '7b95c064e326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='draft', nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('attempts_allowed', sa.Integer(), server_default='1', nullable=False),
    sa.Column('shuffle', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempts_allowed > 0', name=op.f('ck_tests_test_attempts_positive')),
    sa.CheckConstraint('closes_at > opens_at', name=op.f('ck_tests_test_window_ordered')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_tests_test_duration_positive')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_tests_class_id_classes')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_tests_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_tests_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tests'))
    )
    op.create_index('ix_tests_class_status', 'tests', ['class_id', 'status'], unique=False)
    op.create_index(op.f('ix_tests_is_archived'), 'tests', ['is_archived'], unique=False)
    op.create_index('ix_tests_teacher', 'tests', ['teacher_id', 'status'], unique=False)
    op.create_table('test_attempts',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score IS NULL OR score >= 0', name=op.f('ck_test_attempts_attempt_score_non_negative')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_test_attempts_student_id_students')),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_attempts_test_id_tests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_attempts')),
    sa.UniqueConstraint('test_id', 'student_id', 'attempt_no', name=op.f('uq_test_attempts_test_id_student_id_attempt_no'))
    )
    op.create_index('ix_attempts_test_student', 'test_attempts', ['test_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_is_archived'), 'test_attempts', ['is_archived'], unique=False)
    op.create_table('test_questions',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='single', nullable=False),
    sa.Column('points', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_questions_test_id_tests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_questions'))
    )
    op.create_index(op.f('ix_test_questions_is_archived'), 'test_questions', ['is_archived'], unique=False)
    op.create_index('ix_test_questions_test', 'test_questions', ['test_id', 'position'], unique=False)
    op.create_table('test_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('points_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], name=op.f('fk_test_answers_attempt_id_test_attempts')),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], name=op.f('fk_test_answers_question_id_test_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_answers')),
    sa.UniqueConstraint('attempt_id', 'question_id', name=op.f('uq_test_answers_attempt_id_question_id'))
    )
    op.create_index(op.f('ix_test_answers_is_archived'), 'test_answers', ['is_archived'], unique=False)
    op.create_index('ix_test_answers_question', 'test_answers', ['question_id'], unique=False)
    op.create_table('test_options',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], name=op.f('fk_test_options_question_id_test_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_options'))
    )
    op.create_index(op.f('ix_test_options_is_archived'), 'test_options', ['is_archived'], unique=False)
    op.create_index('ix_test_options_question', 'test_options', ['question_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_options_question', table_name='test_options')
    op.drop_index(op.f('ix_test_options_is_archived'), table_name='test_options')
    op.drop_table('test_options')
    op.drop_index('ix_test_answers_question', table_name='test_answers')
    op.drop_index(op.f('ix_test_answers_is_archived'), table_name='test_answers')
    op.drop_table('test_answers')
    op.drop_index('ix_test_questions_test', table_name='test_questions')
    op.drop_index(op.f('ix_test_questions_is_archived'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_test_attempts_is_archived'), table_name='test_attempts')
    op.drop_index('ix_attempts_test_student', table_name='test_attempts')
    op.drop_table('test_attempts')
    op.drop_index('ix_tests_teacher', table_name='tests')
    op.drop_index(op.f('ix_tests_is_archived'), table_name='tests')
    op.drop_index('ix_tests_class_status', table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###
