"""T-027 — ustoz rejasi uchun tasdiqlash sozlamasi (MET-06).

TZ: «Nashr etishdan oldin tasdiqlash talab qilinishi sozlamada yoqib
qoʻyiladi.» Sukut YOQILGAN — metodik baza butun maktab koʻradigan
hujjat, unga tasodifiy qoralama tushib qolmasin.

Revision ID: 90019a426173
Revises: a2c5106fab2f
Create Date: 2026-09-05 10:36:18.323973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90019a426173'
down_revision: Union[str, Sequence[str], None] = 'a2c5106fab2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_settings', sa.Column('curriculum_requires_approval', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_settings', 'curriculum_requires_approval')
    # ### end Alembic commands ###
