"""T-020 elonlar

Revision ID: 6a051cfaee00
Revises: 6608eef4758f
Create Date: 2026-09-01 16:07:59.916055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a051cfaee00'
down_revision: Union[str, Sequence[str], None] = '6608eef4758f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('important', sa.Boolean(), nullable=False),
    sa.Column('recipients_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_announcements_author_id_users')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_announcements_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_index(op.f('ix_announcements_author_id'), 'announcements', ['author_id'], unique=False)
    op.create_index('ix_announcements_created', 'announcements', ['created_at'], unique=False)
    op.create_index(op.f('ix_announcements_is_archived'), 'announcements', ['is_archived'], unique=False)
    op.create_table('announcement_classes',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('fk_announcement_classes_announcement_id_announcements')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_announcement_classes_class_id_classes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement_classes')),
    sa.UniqueConstraint('announcement_id', 'class_id', name=op.f('uq_announcement_classes_announcement_id_class_id'))
    )
    op.create_index('ix_announcement_classes_class', 'announcement_classes', ['class_id'], unique=False)
    op.create_index(op.f('ix_announcement_classes_is_archived'), 'announcement_classes', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcement_classes_is_archived'), table_name='announcement_classes')
    op.drop_index('ix_announcement_classes_class', table_name='announcement_classes')
    op.drop_table('announcement_classes')
    op.drop_index(op.f('ix_announcements_is_archived'), table_name='announcements')
    op.drop_index('ix_announcements_created', table_name='announcements')
    op.drop_index(op.f('ix_announcements_author_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
