"""sorovnomalar

Revision ID: 71aabf2757ae
Revises: 3097b776ce50
Create Date: 2026-09-01 16:34:39.390443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71aabf2757ae'
down_revision: Union[str, Sequence[str], None] = '3097b776ce50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_surveys_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys'))
    )
    op.create_index(op.f('ix_surveys_is_archived'), 'surveys', ['is_archived'], unique=False)
    op.create_table('survey_questions',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_questions_survey_id_surveys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_questions')),
    sa.UniqueConstraint('survey_id', 'position', name=op.f('uq_survey_questions_survey_id_position'))
    )
    op.create_index(op.f('ix_survey_questions_is_archived'), 'survey_questions', ['is_archived'], unique=False)
    op.create_index(op.f('ix_survey_questions_survey_id'), 'survey_questions', ['survey_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('respondent_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['respondent_id'], ['users.id'], name=op.f('fk_survey_responses_respondent_id_users')),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_responses_survey_id_surveys')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_survey_responses_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_responses')),
    sa.UniqueConstraint('survey_id', 'teacher_id', 'respondent_id', name=op.f('uq_survey_responses_survey_id_teacher_id_respondent_id'))
    )
    op.create_index(op.f('ix_survey_responses_is_archived'), 'survey_responses', ['is_archived'], unique=False)
    op.create_index('ix_survey_responses_teacher', 'survey_responses', ['survey_id', 'teacher_id'], unique=False)
    op.create_table('survey_scores',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], name=op.f('fk_survey_scores_question_id_survey_questions')),
    sa.ForeignKeyConstraint(['response_id'], ['survey_responses.id'], name=op.f('fk_survey_scores_response_id_survey_responses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_scores')),
    sa.UniqueConstraint('response_id', 'question_id', name=op.f('uq_survey_scores_response_id_question_id'))
    )
    op.create_index(op.f('ix_survey_scores_is_archived'), 'survey_scores', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_scores_is_archived'), table_name='survey_scores')
    op.drop_table('survey_scores')
    op.drop_index('ix_survey_responses_teacher', table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_is_archived'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_survey_questions_survey_id'), table_name='survey_questions')
    op.drop_index(op.f('ix_survey_questions_is_archived'), table_name='survey_questions')
    op.drop_table('survey_questions')
    op.drop_index(op.f('ix_surveys_is_archived'), table_name='surveys')
    op.drop_table('surveys')
    # ### end Alembic commands ###
