"""sinf atamasi

Revision ID: 267ebe88c542
Revises: 08c0dcdc3cfe
Create Date: 2026-09-01 21:57:30.761333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267ebe88c542'
down_revision: Union[str, Sequence[str], None] = 'a3c9e5f7b1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('title', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'title')
    # ### end Alembic commands ###
