"""t004: refresh_tokens.remember

«Ushbu qurilmada eslab qolish» belgilanmagan sessiya VAQTINCHALIK
boʻlishi kerak. Cookie tomoni ustunsiz ham ishlardi, lekin
`rotate_refresh` har yangilashda muddatni qaytadan 30 kunga
uzaytirib yuborardi — vaqtinchalik sessiya jimgina doimiyga
aylanib qolardi.

Mavjud qatorlar uchun `true`: ular eski xatti-harakat bilan
berilgan va ularni birdan qisqartirish hamma odamni tizimdan
chiqarib yuborardi.

Revision ID: 68f2aa8eb753
Revises: d630c7e260fc
Create Date: 2026-09-03 13:48:44.479262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f2aa8eb753'
down_revision: Union[str, Sequence[str], None] = 'd630c7e260fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('remember', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'remember')
    # ### end Alembic commands ###
