"""drift: is_archived indekslari

Uch jadval (sherikning moduli) `is_archived` ustuniga indekssiz
qolgan edi. Natijada `alembic check` HAR SAFAR yiqilardi — va bu eng
xavflisi: haqiqiy sxema oʻzgarishi shu doimiy shovqin ichida koʻrinmay
qolardi. Loyihada hech narsa oʻchirilmaydi (1-domen qoidasi), yaʼni
har bir roʻyxat soʻrovi `WHERE is_archived = false` bilan ketadi —
indeks bu yerda ixtiyoriy emas.

Revision ID: d630c7e260fc
Revises: bf3e5898befd
Create Date: 2026-09-03 11:42:07.700249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd630c7e260fc'
down_revision: Union[str, Sequence[str], None] = 'bf3e5898befd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cafeteria_menu_items_is_archived'), 'cafeteria_menu_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_curriculum_plans_is_archived'), 'curriculum_plans', ['is_archived'], unique=False)
    op.create_index(op.f('ix_school_settings_is_archived'), 'school_settings', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_settings_is_archived'), table_name='school_settings')
    op.drop_index(op.f('ix_curriculum_plans_is_archived'), table_name='curriculum_plans')
    op.drop_index(op.f('ix_cafeteria_menu_items_is_archived'), table_name='cafeteria_menu_items')
    # ### end Alembic commands ###
