"""T-046..T-049 tolov moduli

Revision ID: bf634d2b4c24
Revises: 492725d06460
Create Date: 2026-09-01 17:30:35.366070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf634d2b4c24'
down_revision: Union[str, Sequence[str], None] = '492725d06460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_intents',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payment_intents_created_by_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_payment_intents_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_intents'))
    )
    op.create_index(op.f('ix_payment_intents_is_archived'), 'payment_intents', ['is_archived'], unique=False)
    op.create_table('payments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('receipt_no', sa.String(length=60), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('is_storno', sa.Boolean(), nullable=False),
    sa.Column('storno_of_id', sa.UUID(), nullable=True),
    sa.Column('storno_reason', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_tx_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_payments_recorded_by_id_users')),
    sa.ForeignKeyConstraint(['storno_of_id'], ['payments.id'], name=op.f('fk_payments_storno_of_id_payments')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_payments_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider_tx_id', name=op.f('uq_payments_provider_tx_id')),
    sa.UniqueConstraint('storno_of_id', name=op.f('uq_payments_storno_of_id'))
    )
    op.create_index(op.f('ix_payments_is_archived'), 'payments', ['is_archived'], unique=False)
    op.create_index('ix_payments_student', 'payments', ['student_id', 'paid_on'], unique=False)
    op.create_table('tuition_charges',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.BigInteger(), nullable=False),
    sa.Column('discount_amount', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_tuition_charges_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tuition_charges')),
    sa.UniqueConstraint('student_id', 'year', 'month', name=op.f('uq_tuition_charges_student_id_year_month'))
    )
    op.create_index(op.f('ix_tuition_charges_is_archived'), 'tuition_charges', ['is_archived'], unique=False)
    op.create_index('ix_tuition_charges_period', 'tuition_charges', ['year', 'month'], unique=False)
    op.create_table('tuition_contracts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('monthly_fee', sa.BigInteger(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_tuition_contracts_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tuition_contracts'))
    )
    op.create_index(op.f('ix_tuition_contracts_is_archived'), 'tuition_contracts', ['is_archived'], unique=False)
    op.create_index('ix_tuition_contracts_student', 'tuition_contracts', ['student_id', 'is_archived'], unique=False)
    op.create_table('tuition_discounts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_tuition_discounts_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tuition_discounts'))
    )
    op.create_index(op.f('ix_tuition_discounts_is_archived'), 'tuition_discounts', ['is_archived'], unique=False)
    op.create_index('ix_tuition_discounts_student', 'tuition_discounts', ['student_id', 'is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tuition_discounts_student', table_name='tuition_discounts')
    op.drop_index(op.f('ix_tuition_discounts_is_archived'), table_name='tuition_discounts')
    op.drop_table('tuition_discounts')
    op.drop_index('ix_tuition_contracts_student', table_name='tuition_contracts')
    op.drop_index(op.f('ix_tuition_contracts_is_archived'), table_name='tuition_contracts')
    op.drop_table('tuition_contracts')
    op.drop_index('ix_tuition_charges_period', table_name='tuition_charges')
    op.drop_index(op.f('ix_tuition_charges_is_archived'), table_name='tuition_charges')
    op.drop_table('tuition_charges')
    op.drop_index('ix_payments_student', table_name='payments')
    op.drop_index(op.f('ix_payments_is_archived'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_intents_is_archived'), table_name='payment_intents')
    op.drop_table('payment_intents')
    # ### end Alembic commands ###
