"""t005 huquqlar markazi bolim istisnolari

Revision ID: 4dd12fea2cb6
Revises: 469bc6adbc99
Create Date: 2026-08-31 03:54:34.909172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dd12fea2cb6'
down_revision: Union[str, Sequence[str], None] = '469bc6adbc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('section_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'section_overrides')
    # ### end Alembic commands ###
